version: '3.0'

x-uffizzi:
  ingress:
    service: frontend
    port: 80

services:
  backend:
    image: '${ACTIVEPIECES_BACKEND_IMAGE}'
    ports:
      - 3000:3000
    environment:
      - AP_NODE_EXECUTABLE_PATH=/usr/local/bin/node
      - AP_POSTGRES_DATABASE=activepieces
      - AP_POSTGRES_HOST=localhost
      - AP_POSTGRES_PASSWORD=A79Vm5D4p2VQHOp2gd5
      - AP_POSTGRES_PORT=5432
      - AP_POSTGRES_USERNAME=postgres
      - AP_REDIS_HOST=localhost
      - AP_REDIS_PORT=6379
      - AP_FRONTEND_URL=http://localhost:80
      - AP_BACKEND_URL=http://localhost:80/api
    deploy:
      resources:
        limits:
          memory: 500M 

  frontend:
    image: '${ACTIVEPIECES_FRONTEND_IMAGE}'
    container_name: activepieces-frontend
    volumes:
      - ./.github/uffizzi/nginx:/etc/nginx/
    ports:
      - 80:80
    deploy:
      resources:
        limits:
          memory: 500M 

  postgres:
    image: postgres:14.4
    container_name: activepieces-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=activepieces
      - POSTGRES_PASSWORD=A79Vm5D4p2VQHOp2gd5
      - POSTGRES_USER=postgres

  redis:
    image: redis:7.0.7
    container_name: activepieces-redis
